DROP DATABASE eTracker_db;

CREATE DATABASE eTracker_db;

USE eTracker_db

-- DEPARTMENT TABLE 
CREATE TABLE department(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30)
)


-- ROLE TABLE
CREATE TABLE role(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30),
    salary DECIMAL,
    department_id INT NOT NULL,

)


-- EMPLOYEE TABLE 
CREATE TABLE employee()